// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_state_blob.proto

package org.libra.grpc.types;

public final class AccountStateBlobOuterClass {
  private AccountStateBlobOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccountStateBlobOrBuilder extends
      // @@protoc_insertion_point(interface_extends:types.AccountStateBlob)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes blob = 1;</code>
     */
    com.google.protobuf.ByteString getBlob();
  }
  /**
   * Protobuf type {@code types.AccountStateBlob}
   */
  public  static final class AccountStateBlob extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:types.AccountStateBlob)
      AccountStateBlobOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccountStateBlob.newBuilder() to construct.
    private AccountStateBlob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountStateBlob() {
      blob_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AccountStateBlob(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              blob_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateBlob_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateBlob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.class, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.Builder.class);
    }

    public static final int BLOB_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString blob_;
    /**
     * <code>bytes blob = 1;</code>
     */
    public com.google.protobuf.ByteString getBlob() {
      return blob_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!blob_.isEmpty()) {
        output.writeBytes(1, blob_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!blob_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, blob_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob)) {
        return super.equals(obj);
      }
      org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob other = (org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob) obj;

      if (!getBlob()
          .equals(other.getBlob())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOB_FIELD_NUMBER;
      hash = (53 * hash) + getBlob().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code types.AccountStateBlob}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:types.AccountStateBlob)
        org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateBlob_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateBlob_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.class, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.Builder.class);
      }

      // Construct using org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blob_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateBlob_descriptor;
      }

      @java.lang.Override
      public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob getDefaultInstanceForType() {
        return org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.getDefaultInstance();
      }

      @java.lang.Override
      public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob build() {
        org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob buildPartial() {
        org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob result = new org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob(this);
        result.blob_ = blob_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob) {
          return mergeFrom((org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob other) {
        if (other == org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.getDefaultInstance()) return this;
        if (other.getBlob() != com.google.protobuf.ByteString.EMPTY) {
          setBlob(other.getBlob());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString blob_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes blob = 1;</code>
       */
      public com.google.protobuf.ByteString getBlob() {
        return blob_;
      }
      /**
       * <code>bytes blob = 1;</code>
       */
      public Builder setBlob(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        blob_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes blob = 1;</code>
       */
      public Builder clearBlob() {
        
        blob_ = getDefaultInstance().getBlob();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:types.AccountStateBlob)
    }

    // @@protoc_insertion_point(class_scope:types.AccountStateBlob)
    private static final org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob();
    }

    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountStateBlob>
        PARSER = new com.google.protobuf.AbstractParser<AccountStateBlob>() {
      @java.lang.Override
      public AccountStateBlob parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountStateBlob(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccountStateBlob> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountStateBlob> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AccountStateWithProofOrBuilder extends
      // @@protoc_insertion_point(interface_extends:types.AccountStateWithProof)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 version = 1;</code>
     */
    long getVersion();

    /**
     * <code>.types.AccountStateBlob blob = 2;</code>
     */
    boolean hasBlob();
    /**
     * <code>.types.AccountStateBlob blob = 2;</code>
     */
    org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob getBlob();
    /**
     * <code>.types.AccountStateBlob blob = 2;</code>
     */
    org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlobOrBuilder getBlobOrBuilder();

    /**
     * <code>.types.AccountStateProof proof = 3;</code>
     */
    boolean hasProof();
    /**
     * <code>.types.AccountStateProof proof = 3;</code>
     */
    org.libra.grpc.types.Proof.AccountStateProof getProof();
    /**
     * <code>.types.AccountStateProof proof = 3;</code>
     */
    org.libra.grpc.types.Proof.AccountStateProofOrBuilder getProofOrBuilder();
  }
  /**
   * Protobuf type {@code types.AccountStateWithProof}
   */
  public  static final class AccountStateWithProof extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:types.AccountStateWithProof)
      AccountStateWithProofOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccountStateWithProof.newBuilder() to construct.
    private AccountStateWithProof(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountStateWithProof() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AccountStateWithProof(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readUInt64();
              break;
            }
            case 18: {
              org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.Builder subBuilder = null;
              if (blob_ != null) {
                subBuilder = blob_.toBuilder();
              }
              blob_ = input.readMessage(org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(blob_);
                blob_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              org.libra.grpc.types.Proof.AccountStateProof.Builder subBuilder = null;
              if (proof_ != null) {
                subBuilder = proof_.toBuilder();
              }
              proof_ = input.readMessage(org.libra.grpc.types.Proof.AccountStateProof.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(proof_);
                proof_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateWithProof_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateWithProof_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof.class, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <code>uint64 version = 1;</code>
     */
    public long getVersion() {
      return version_;
    }

    public static final int BLOB_FIELD_NUMBER = 2;
    private org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob blob_;
    /**
     * <code>.types.AccountStateBlob blob = 2;</code>
     */
    public boolean hasBlob() {
      return blob_ != null;
    }
    /**
     * <code>.types.AccountStateBlob blob = 2;</code>
     */
    public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob getBlob() {
      return blob_ == null ? org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.getDefaultInstance() : blob_;
    }
    /**
     * <code>.types.AccountStateBlob blob = 2;</code>
     */
    public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlobOrBuilder getBlobOrBuilder() {
      return getBlob();
    }

    public static final int PROOF_FIELD_NUMBER = 3;
    private org.libra.grpc.types.Proof.AccountStateProof proof_;
    /**
     * <code>.types.AccountStateProof proof = 3;</code>
     */
    public boolean hasProof() {
      return proof_ != null;
    }
    /**
     * <code>.types.AccountStateProof proof = 3;</code>
     */
    public org.libra.grpc.types.Proof.AccountStateProof getProof() {
      return proof_ == null ? org.libra.grpc.types.Proof.AccountStateProof.getDefaultInstance() : proof_;
    }
    /**
     * <code>.types.AccountStateProof proof = 3;</code>
     */
    public org.libra.grpc.types.Proof.AccountStateProofOrBuilder getProofOrBuilder() {
      return getProof();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0L) {
        output.writeUInt64(1, version_);
      }
      if (blob_ != null) {
        output.writeMessage(2, getBlob());
      }
      if (proof_ != null) {
        output.writeMessage(3, getProof());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, version_);
      }
      if (blob_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBlob());
      }
      if (proof_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getProof());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof)) {
        return super.equals(obj);
      }
      org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof other = (org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (hasBlob() != other.hasBlob()) return false;
      if (hasBlob()) {
        if (!getBlob()
            .equals(other.getBlob())) return false;
      }
      if (hasProof() != other.hasProof()) return false;
      if (hasProof()) {
        if (!getProof()
            .equals(other.getProof())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      if (hasBlob()) {
        hash = (37 * hash) + BLOB_FIELD_NUMBER;
        hash = (53 * hash) + getBlob().hashCode();
      }
      if (hasProof()) {
        hash = (37 * hash) + PROOF_FIELD_NUMBER;
        hash = (53 * hash) + getProof().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code types.AccountStateWithProof}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:types.AccountStateWithProof)
        org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProofOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateWithProof_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateWithProof_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof.class, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof.Builder.class);
      }

      // Construct using org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0L;

        if (blobBuilder_ == null) {
          blob_ = null;
        } else {
          blob_ = null;
          blobBuilder_ = null;
        }
        if (proofBuilder_ == null) {
          proof_ = null;
        } else {
          proof_ = null;
          proofBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.libra.grpc.types.AccountStateBlobOuterClass.internal_static_types_AccountStateWithProof_descriptor;
      }

      @java.lang.Override
      public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof getDefaultInstanceForType() {
        return org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof.getDefaultInstance();
      }

      @java.lang.Override
      public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof build() {
        org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof buildPartial() {
        org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof result = new org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof(this);
        result.version_ = version_;
        if (blobBuilder_ == null) {
          result.blob_ = blob_;
        } else {
          result.blob_ = blobBuilder_.build();
        }
        if (proofBuilder_ == null) {
          result.proof_ = proof_;
        } else {
          result.proof_ = proofBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof) {
          return mergeFrom((org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof other) {
        if (other == org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof.getDefaultInstance()) return this;
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        if (other.hasBlob()) {
          mergeBlob(other.getBlob());
        }
        if (other.hasProof()) {
          mergeProof(other.getProof());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long version_ ;
      /**
       * <code>uint64 version = 1;</code>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <code>uint64 version = 1;</code>
       */
      public Builder setVersion(long value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0L;
        onChanged();
        return this;
      }

      private org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob blob_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.Builder, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlobOrBuilder> blobBuilder_;
      /**
       * <code>.types.AccountStateBlob blob = 2;</code>
       */
      public boolean hasBlob() {
        return blobBuilder_ != null || blob_ != null;
      }
      /**
       * <code>.types.AccountStateBlob blob = 2;</code>
       */
      public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob getBlob() {
        if (blobBuilder_ == null) {
          return blob_ == null ? org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.getDefaultInstance() : blob_;
        } else {
          return blobBuilder_.getMessage();
        }
      }
      /**
       * <code>.types.AccountStateBlob blob = 2;</code>
       */
      public Builder setBlob(org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob value) {
        if (blobBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          blob_ = value;
          onChanged();
        } else {
          blobBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.types.AccountStateBlob blob = 2;</code>
       */
      public Builder setBlob(
          org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.Builder builderForValue) {
        if (blobBuilder_ == null) {
          blob_ = builderForValue.build();
          onChanged();
        } else {
          blobBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.types.AccountStateBlob blob = 2;</code>
       */
      public Builder mergeBlob(org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob value) {
        if (blobBuilder_ == null) {
          if (blob_ != null) {
            blob_ =
              org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.newBuilder(blob_).mergeFrom(value).buildPartial();
          } else {
            blob_ = value;
          }
          onChanged();
        } else {
          blobBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.types.AccountStateBlob blob = 2;</code>
       */
      public Builder clearBlob() {
        if (blobBuilder_ == null) {
          blob_ = null;
          onChanged();
        } else {
          blob_ = null;
          blobBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.types.AccountStateBlob blob = 2;</code>
       */
      public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.Builder getBlobBuilder() {
        
        onChanged();
        return getBlobFieldBuilder().getBuilder();
      }
      /**
       * <code>.types.AccountStateBlob blob = 2;</code>
       */
      public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlobOrBuilder getBlobOrBuilder() {
        if (blobBuilder_ != null) {
          return blobBuilder_.getMessageOrBuilder();
        } else {
          return blob_ == null ?
              org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.getDefaultInstance() : blob_;
        }
      }
      /**
       * <code>.types.AccountStateBlob blob = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.Builder, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlobOrBuilder> 
          getBlobFieldBuilder() {
        if (blobBuilder_ == null) {
          blobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlob.Builder, org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateBlobOrBuilder>(
                  getBlob(),
                  getParentForChildren(),
                  isClean());
          blob_ = null;
        }
        return blobBuilder_;
      }

      private org.libra.grpc.types.Proof.AccountStateProof proof_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.libra.grpc.types.Proof.AccountStateProof, org.libra.grpc.types.Proof.AccountStateProof.Builder, org.libra.grpc.types.Proof.AccountStateProofOrBuilder> proofBuilder_;
      /**
       * <code>.types.AccountStateProof proof = 3;</code>
       */
      public boolean hasProof() {
        return proofBuilder_ != null || proof_ != null;
      }
      /**
       * <code>.types.AccountStateProof proof = 3;</code>
       */
      public org.libra.grpc.types.Proof.AccountStateProof getProof() {
        if (proofBuilder_ == null) {
          return proof_ == null ? org.libra.grpc.types.Proof.AccountStateProof.getDefaultInstance() : proof_;
        } else {
          return proofBuilder_.getMessage();
        }
      }
      /**
       * <code>.types.AccountStateProof proof = 3;</code>
       */
      public Builder setProof(org.libra.grpc.types.Proof.AccountStateProof value) {
        if (proofBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          proof_ = value;
          onChanged();
        } else {
          proofBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.types.AccountStateProof proof = 3;</code>
       */
      public Builder setProof(
          org.libra.grpc.types.Proof.AccountStateProof.Builder builderForValue) {
        if (proofBuilder_ == null) {
          proof_ = builderForValue.build();
          onChanged();
        } else {
          proofBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.types.AccountStateProof proof = 3;</code>
       */
      public Builder mergeProof(org.libra.grpc.types.Proof.AccountStateProof value) {
        if (proofBuilder_ == null) {
          if (proof_ != null) {
            proof_ =
              org.libra.grpc.types.Proof.AccountStateProof.newBuilder(proof_).mergeFrom(value).buildPartial();
          } else {
            proof_ = value;
          }
          onChanged();
        } else {
          proofBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.types.AccountStateProof proof = 3;</code>
       */
      public Builder clearProof() {
        if (proofBuilder_ == null) {
          proof_ = null;
          onChanged();
        } else {
          proof_ = null;
          proofBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.types.AccountStateProof proof = 3;</code>
       */
      public org.libra.grpc.types.Proof.AccountStateProof.Builder getProofBuilder() {
        
        onChanged();
        return getProofFieldBuilder().getBuilder();
      }
      /**
       * <code>.types.AccountStateProof proof = 3;</code>
       */
      public org.libra.grpc.types.Proof.AccountStateProofOrBuilder getProofOrBuilder() {
        if (proofBuilder_ != null) {
          return proofBuilder_.getMessageOrBuilder();
        } else {
          return proof_ == null ?
              org.libra.grpc.types.Proof.AccountStateProof.getDefaultInstance() : proof_;
        }
      }
      /**
       * <code>.types.AccountStateProof proof = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.libra.grpc.types.Proof.AccountStateProof, org.libra.grpc.types.Proof.AccountStateProof.Builder, org.libra.grpc.types.Proof.AccountStateProofOrBuilder> 
          getProofFieldBuilder() {
        if (proofBuilder_ == null) {
          proofBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.libra.grpc.types.Proof.AccountStateProof, org.libra.grpc.types.Proof.AccountStateProof.Builder, org.libra.grpc.types.Proof.AccountStateProofOrBuilder>(
                  getProof(),
                  getParentForChildren(),
                  isClean());
          proof_ = null;
        }
        return proofBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:types.AccountStateWithProof)
    }

    // @@protoc_insertion_point(class_scope:types.AccountStateWithProof)
    private static final org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof();
    }

    public static org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountStateWithProof>
        PARSER = new com.google.protobuf.AbstractParser<AccountStateWithProof>() {
      @java.lang.Override
      public AccountStateWithProof parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountStateWithProof(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccountStateWithProof> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountStateWithProof> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.libra.grpc.types.AccountStateBlobOuterClass.AccountStateWithProof getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_AccountStateBlob_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_AccountStateBlob_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_AccountStateWithProof_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_AccountStateWithProof_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030account_state_blob.proto\022\005types\032\013proof" +
      ".proto\" \n\020AccountStateBlob\022\014\n\004blob\030\001 \001(\014" +
      "\"x\n\025AccountStateWithProof\022\017\n\007version\030\001 \001" +
      "(\004\022%\n\004blob\030\002 \001(\0132\027.types.AccountStateBlo" +
      "b\022\'\n\005proof\030\003 \001(\0132\030.types.AccountStatePro" +
      "ofB\026\n\024org.libra.grpc.typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.libra.grpc.types.Proof.getDescriptor(),
        }, assigner);
    internal_static_types_AccountStateBlob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_types_AccountStateBlob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_AccountStateBlob_descriptor,
        new java.lang.String[] { "Blob", });
    internal_static_types_AccountStateWithProof_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_types_AccountStateWithProof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_AccountStateWithProof_descriptor,
        new java.lang.String[] { "Version", "Blob", "Proof", });
    org.libra.grpc.types.Proof.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
