// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vm_errors.proto

package org.libra.grpc.types;

public final class VmErrors {
  private VmErrors() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VMStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:types.VMStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * e.g. assertion violation, out of gas
     * </pre>
     *
     * <code>uint64 major_status = 1;</code>
     */
    long getMajorStatus();

    /**
     * <pre>
     * Any substatus code. e.g. assertion error number
     * </pre>
     *
     * <code>bool has_sub_status = 2;</code>
     */
    boolean getHasSubStatus();

    /**
     * <code>uint64 sub_status = 3;</code>
     */
    long getSubStatus();

    /**
     * <code>bool has_message = 4;</code>
     */
    boolean getHasMessage();

    /**
     * <code>string message = 5;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 5;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * The statuses and errors produced by the VM can be categorized into a
   * couple different types:
   * 1. Validation Statuses: all the errors that can (/should) be
   *    the result of executing the prologue -- these are primarily used by
   *    the vm validator and AC.
   * 2. Verification Errors: errors that are the result of performing
   *    bytecode verification (happens at the time of publishing).
   * 3. VM Invariant Errors: errors that arise from an internal invariant of
   *    the VM being violated. These signify a problem with either the VM or
   *    bytecode verifier.
   * 4. Binary Errors: errors that can occur during the process of
   *    deserialization of a transaction.
   * 5. Runtime Statuses: errors that can arise from the execution of a
   *    transaction (assuming the prologue executes without error). These are
   *    errors that can occur during execution due to things such as division
   *    by zero, running out of gas, etc. These do not signify an issue with
   *    the VM.
   * </pre>
   *
   * Protobuf type {@code types.VMStatus}
   */
  public  static final class VMStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:types.VMStatus)
      VMStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VMStatus.newBuilder() to construct.
    private VMStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VMStatus() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VMStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              majorStatus_ = input.readUInt64();
              break;
            }
            case 16: {

              hasSubStatus_ = input.readBool();
              break;
            }
            case 24: {

              subStatus_ = input.readUInt64();
              break;
            }
            case 32: {

              hasMessage_ = input.readBool();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.libra.grpc.types.VmErrors.internal_static_types_VMStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.libra.grpc.types.VmErrors.internal_static_types_VMStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.libra.grpc.types.VmErrors.VMStatus.class, org.libra.grpc.types.VmErrors.VMStatus.Builder.class);
    }

    public static final int MAJOR_STATUS_FIELD_NUMBER = 1;
    private long majorStatus_;
    /**
     * <pre>
     * e.g. assertion violation, out of gas
     * </pre>
     *
     * <code>uint64 major_status = 1;</code>
     */
    public long getMajorStatus() {
      return majorStatus_;
    }

    public static final int HAS_SUB_STATUS_FIELD_NUMBER = 2;
    private boolean hasSubStatus_;
    /**
     * <pre>
     * Any substatus code. e.g. assertion error number
     * </pre>
     *
     * <code>bool has_sub_status = 2;</code>
     */
    public boolean getHasSubStatus() {
      return hasSubStatus_;
    }

    public static final int SUB_STATUS_FIELD_NUMBER = 3;
    private long subStatus_;
    /**
     * <code>uint64 sub_status = 3;</code>
     */
    public long getSubStatus() {
      return subStatus_;
    }

    public static final int HAS_MESSAGE_FIELD_NUMBER = 4;
    private boolean hasMessage_;
    /**
     * <code>bool has_message = 4;</code>
     */
    public boolean getHasMessage() {
      return hasMessage_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 5;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (majorStatus_ != 0L) {
        output.writeUInt64(1, majorStatus_);
      }
      if (hasSubStatus_ != false) {
        output.writeBool(2, hasSubStatus_);
      }
      if (subStatus_ != 0L) {
        output.writeUInt64(3, subStatus_);
      }
      if (hasMessage_ != false) {
        output.writeBool(4, hasMessage_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (majorStatus_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, majorStatus_);
      }
      if (hasSubStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, hasSubStatus_);
      }
      if (subStatus_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, subStatus_);
      }
      if (hasMessage_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasMessage_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.libra.grpc.types.VmErrors.VMStatus)) {
        return super.equals(obj);
      }
      org.libra.grpc.types.VmErrors.VMStatus other = (org.libra.grpc.types.VmErrors.VMStatus) obj;

      if (getMajorStatus()
          != other.getMajorStatus()) return false;
      if (getHasSubStatus()
          != other.getHasSubStatus()) return false;
      if (getSubStatus()
          != other.getSubStatus()) return false;
      if (getHasMessage()
          != other.getHasMessage()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAJOR_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMajorStatus());
      hash = (37 * hash) + HAS_SUB_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasSubStatus());
      hash = (37 * hash) + SUB_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSubStatus());
      hash = (37 * hash) + HAS_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasMessage());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.VmErrors.VMStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.libra.grpc.types.VmErrors.VMStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The statuses and errors produced by the VM can be categorized into a
     * couple different types:
     * 1. Validation Statuses: all the errors that can (/should) be
     *    the result of executing the prologue -- these are primarily used by
     *    the vm validator and AC.
     * 2. Verification Errors: errors that are the result of performing
     *    bytecode verification (happens at the time of publishing).
     * 3. VM Invariant Errors: errors that arise from an internal invariant of
     *    the VM being violated. These signify a problem with either the VM or
     *    bytecode verifier.
     * 4. Binary Errors: errors that can occur during the process of
     *    deserialization of a transaction.
     * 5. Runtime Statuses: errors that can arise from the execution of a
     *    transaction (assuming the prologue executes without error). These are
     *    errors that can occur during execution due to things such as division
     *    by zero, running out of gas, etc. These do not signify an issue with
     *    the VM.
     * </pre>
     *
     * Protobuf type {@code types.VMStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:types.VMStatus)
        org.libra.grpc.types.VmErrors.VMStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.libra.grpc.types.VmErrors.internal_static_types_VMStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.libra.grpc.types.VmErrors.internal_static_types_VMStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.libra.grpc.types.VmErrors.VMStatus.class, org.libra.grpc.types.VmErrors.VMStatus.Builder.class);
      }

      // Construct using org.libra.grpc.types.VmErrors.VMStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        majorStatus_ = 0L;

        hasSubStatus_ = false;

        subStatus_ = 0L;

        hasMessage_ = false;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.libra.grpc.types.VmErrors.internal_static_types_VMStatus_descriptor;
      }

      @java.lang.Override
      public org.libra.grpc.types.VmErrors.VMStatus getDefaultInstanceForType() {
        return org.libra.grpc.types.VmErrors.VMStatus.getDefaultInstance();
      }

      @java.lang.Override
      public org.libra.grpc.types.VmErrors.VMStatus build() {
        org.libra.grpc.types.VmErrors.VMStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.libra.grpc.types.VmErrors.VMStatus buildPartial() {
        org.libra.grpc.types.VmErrors.VMStatus result = new org.libra.grpc.types.VmErrors.VMStatus(this);
        result.majorStatus_ = majorStatus_;
        result.hasSubStatus_ = hasSubStatus_;
        result.subStatus_ = subStatus_;
        result.hasMessage_ = hasMessage_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.libra.grpc.types.VmErrors.VMStatus) {
          return mergeFrom((org.libra.grpc.types.VmErrors.VMStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.libra.grpc.types.VmErrors.VMStatus other) {
        if (other == org.libra.grpc.types.VmErrors.VMStatus.getDefaultInstance()) return this;
        if (other.getMajorStatus() != 0L) {
          setMajorStatus(other.getMajorStatus());
        }
        if (other.getHasSubStatus() != false) {
          setHasSubStatus(other.getHasSubStatus());
        }
        if (other.getSubStatus() != 0L) {
          setSubStatus(other.getSubStatus());
        }
        if (other.getHasMessage() != false) {
          setHasMessage(other.getHasMessage());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.libra.grpc.types.VmErrors.VMStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.libra.grpc.types.VmErrors.VMStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long majorStatus_ ;
      /**
       * <pre>
       * e.g. assertion violation, out of gas
       * </pre>
       *
       * <code>uint64 major_status = 1;</code>
       */
      public long getMajorStatus() {
        return majorStatus_;
      }
      /**
       * <pre>
       * e.g. assertion violation, out of gas
       * </pre>
       *
       * <code>uint64 major_status = 1;</code>
       */
      public Builder setMajorStatus(long value) {
        
        majorStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g. assertion violation, out of gas
       * </pre>
       *
       * <code>uint64 major_status = 1;</code>
       */
      public Builder clearMajorStatus() {
        
        majorStatus_ = 0L;
        onChanged();
        return this;
      }

      private boolean hasSubStatus_ ;
      /**
       * <pre>
       * Any substatus code. e.g. assertion error number
       * </pre>
       *
       * <code>bool has_sub_status = 2;</code>
       */
      public boolean getHasSubStatus() {
        return hasSubStatus_;
      }
      /**
       * <pre>
       * Any substatus code. e.g. assertion error number
       * </pre>
       *
       * <code>bool has_sub_status = 2;</code>
       */
      public Builder setHasSubStatus(boolean value) {
        
        hasSubStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any substatus code. e.g. assertion error number
       * </pre>
       *
       * <code>bool has_sub_status = 2;</code>
       */
      public Builder clearHasSubStatus() {
        
        hasSubStatus_ = false;
        onChanged();
        return this;
      }

      private long subStatus_ ;
      /**
       * <code>uint64 sub_status = 3;</code>
       */
      public long getSubStatus() {
        return subStatus_;
      }
      /**
       * <code>uint64 sub_status = 3;</code>
       */
      public Builder setSubStatus(long value) {
        
        subStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 sub_status = 3;</code>
       */
      public Builder clearSubStatus() {
        
        subStatus_ = 0L;
        onChanged();
        return this;
      }

      private boolean hasMessage_ ;
      /**
       * <code>bool has_message = 4;</code>
       */
      public boolean getHasMessage() {
        return hasMessage_;
      }
      /**
       * <code>bool has_message = 4;</code>
       */
      public Builder setHasMessage(boolean value) {
        
        hasMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool has_message = 4;</code>
       */
      public Builder clearHasMessage() {
        
        hasMessage_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 5;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 5;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 5;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 5;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:types.VMStatus)
    }

    // @@protoc_insertion_point(class_scope:types.VMStatus)
    private static final org.libra.grpc.types.VmErrors.VMStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.libra.grpc.types.VmErrors.VMStatus();
    }

    public static org.libra.grpc.types.VmErrors.VMStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VMStatus>
        PARSER = new com.google.protobuf.AbstractParser<VMStatus>() {
      @java.lang.Override
      public VMStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VMStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VMStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VMStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.libra.grpc.types.VmErrors.VMStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_VMStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_VMStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017vm_errors.proto\022\005types\"r\n\010VMStatus\022\024\n\014" +
      "major_status\030\001 \001(\004\022\026\n\016has_sub_status\030\002 \001" +
      "(\010\022\022\n\nsub_status\030\003 \001(\004\022\023\n\013has_message\030\004 " +
      "\001(\010\022\017\n\007message\030\005 \001(\tB\026\n\024org.libra.grpc.t" +
      "ypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_types_VMStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_types_VMStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_VMStatus_descriptor,
        new java.lang.String[] { "MajorStatus", "HasSubStatus", "SubStatus", "HasMessage", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
