// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mempool_status.proto

package org.libra.grpc.types;

public final class MempoolStatus {
  private MempoolStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code mempool_status.MempoolAddTransactionStatusCode}
   */
  public enum MempoolAddTransactionStatusCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Transaction was sent to Mempool
     * </pre>
     *
     * <code>Valid = 0;</code>
     */
    Valid(0),
    /**
     * <pre>
     * The sender does not have enough balance for the transaction.
     * </pre>
     *
     * <code>InsufficientBalance = 1;</code>
     */
    InsufficientBalance(1),
    /**
     * <pre>
     * Sequence number is old, etc.
     * </pre>
     *
     * <code>InvalidSeqNumber = 2;</code>
     */
    InvalidSeqNumber(2),
    /**
     * <pre>
     * Mempool is full (reached max global capacity)
     * </pre>
     *
     * <code>MempoolIsFull = 3;</code>
     */
    MempoolIsFull(3),
    /**
     * <pre>
     * Account reached max capacity per account
     * </pre>
     *
     * <code>TooManyTransactions = 4;</code>
     */
    TooManyTransactions(4),
    /**
     * <pre>
     * Invalid update. Only gas price increase is allowed
     * </pre>
     *
     * <code>InvalidUpdate = 5;</code>
     */
    InvalidUpdate(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Transaction was sent to Mempool
     * </pre>
     *
     * <code>Valid = 0;</code>
     */
    public static final int Valid_VALUE = 0;
    /**
     * <pre>
     * The sender does not have enough balance for the transaction.
     * </pre>
     *
     * <code>InsufficientBalance = 1;</code>
     */
    public static final int InsufficientBalance_VALUE = 1;
    /**
     * <pre>
     * Sequence number is old, etc.
     * </pre>
     *
     * <code>InvalidSeqNumber = 2;</code>
     */
    public static final int InvalidSeqNumber_VALUE = 2;
    /**
     * <pre>
     * Mempool is full (reached max global capacity)
     * </pre>
     *
     * <code>MempoolIsFull = 3;</code>
     */
    public static final int MempoolIsFull_VALUE = 3;
    /**
     * <pre>
     * Account reached max capacity per account
     * </pre>
     *
     * <code>TooManyTransactions = 4;</code>
     */
    public static final int TooManyTransactions_VALUE = 4;
    /**
     * <pre>
     * Invalid update. Only gas price increase is allowed
     * </pre>
     *
     * <code>InvalidUpdate = 5;</code>
     */
    public static final int InvalidUpdate_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MempoolAddTransactionStatusCode valueOf(int value) {
      return forNumber(value);
    }

    public static MempoolAddTransactionStatusCode forNumber(int value) {
      switch (value) {
        case 0: return Valid;
        case 1: return InsufficientBalance;
        case 2: return InvalidSeqNumber;
        case 3: return MempoolIsFull;
        case 4: return TooManyTransactions;
        case 5: return InvalidUpdate;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MempoolAddTransactionStatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MempoolAddTransactionStatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MempoolAddTransactionStatusCode>() {
            public MempoolAddTransactionStatusCode findValueByNumber(int number) {
              return MempoolAddTransactionStatusCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.libra.grpc.types.MempoolStatus.getDescriptor().getEnumTypes().get(0);
    }

    private static final MempoolAddTransactionStatusCode[] VALUES = values();

    public static MempoolAddTransactionStatusCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MempoolAddTransactionStatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mempool_status.MempoolAddTransactionStatusCode)
  }

  public interface MempoolAddTransactionStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mempool_status.MempoolAddTransactionStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.mempool_status.MempoolAddTransactionStatusCode code = 1;</code>
     */
    int getCodeValue();
    /**
     * <code>.mempool_status.MempoolAddTransactionStatusCode code = 1;</code>
     */
    org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode getCode();

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code mempool_status.MempoolAddTransactionStatus}
   */
  public  static final class MempoolAddTransactionStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mempool_status.MempoolAddTransactionStatus)
      MempoolAddTransactionStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MempoolAddTransactionStatus.newBuilder() to construct.
    private MempoolAddTransactionStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MempoolAddTransactionStatus() {
      code_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MempoolAddTransactionStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.libra.grpc.types.MempoolStatus.internal_static_mempool_status_MempoolAddTransactionStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.libra.grpc.types.MempoolStatus.internal_static_mempool_status_MempoolAddTransactionStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus.class, org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>.mempool_status.MempoolAddTransactionStatusCode code = 1;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.mempool_status.MempoolAddTransactionStatusCode code = 1;</code>
     */
    public org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode getCode() {
      @SuppressWarnings("deprecation")
      org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode result = org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode.valueOf(code_);
      return result == null ? org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode.Valid.getNumber()) {
        output.writeEnum(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode.Valid.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus)) {
        return super.equals(obj);
      }
      org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus other = (org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus) obj;

      if (code_ != other.code_) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mempool_status.MempoolAddTransactionStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mempool_status.MempoolAddTransactionStatus)
        org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.libra.grpc.types.MempoolStatus.internal_static_mempool_status_MempoolAddTransactionStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.libra.grpc.types.MempoolStatus.internal_static_mempool_status_MempoolAddTransactionStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus.class, org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus.Builder.class);
      }

      // Construct using org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.libra.grpc.types.MempoolStatus.internal_static_mempool_status_MempoolAddTransactionStatus_descriptor;
      }

      @java.lang.Override
      public org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus getDefaultInstanceForType() {
        return org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus.getDefaultInstance();
      }

      @java.lang.Override
      public org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus build() {
        org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus buildPartial() {
        org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus result = new org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus(this);
        result.code_ = code_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus) {
          return mergeFrom((org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus other) {
        if (other == org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ = 0;
      /**
       * <code>.mempool_status.MempoolAddTransactionStatusCode code = 1;</code>
       */
      public int getCodeValue() {
        return code_;
      }
      /**
       * <code>.mempool_status.MempoolAddTransactionStatusCode code = 1;</code>
       */
      public Builder setCodeValue(int value) {
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.mempool_status.MempoolAddTransactionStatusCode code = 1;</code>
       */
      public org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode getCode() {
        @SuppressWarnings("deprecation")
        org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode result = org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode.valueOf(code_);
        return result == null ? org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.mempool_status.MempoolAddTransactionStatusCode code = 1;</code>
       */
      public Builder setCode(org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.mempool_status.MempoolAddTransactionStatusCode code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mempool_status.MempoolAddTransactionStatus)
    }

    // @@protoc_insertion_point(class_scope:mempool_status.MempoolAddTransactionStatus)
    private static final org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus();
    }

    public static org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MempoolAddTransactionStatus>
        PARSER = new com.google.protobuf.AbstractParser<MempoolAddTransactionStatus>() {
      @java.lang.Override
      public MempoolAddTransactionStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MempoolAddTransactionStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MempoolAddTransactionStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MempoolAddTransactionStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.libra.grpc.types.MempoolStatus.MempoolAddTransactionStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mempool_status_MempoolAddTransactionStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mempool_status_MempoolAddTransactionStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024mempool_status.proto\022\016mempool_status\"m" +
      "\n\033MempoolAddTransactionStatus\022=\n\004code\030\001 " +
      "\001(\0162/.mempool_status.MempoolAddTransacti" +
      "onStatusCode\022\017\n\007message\030\002 \001(\t*\232\001\n\037Mempoo" +
      "lAddTransactionStatusCode\022\t\n\005Valid\020\000\022\027\n\023" +
      "InsufficientBalance\020\001\022\024\n\020InvalidSeqNumbe" +
      "r\020\002\022\021\n\rMempoolIsFull\020\003\022\027\n\023TooManyTransac" +
      "tions\020\004\022\021\n\rInvalidUpdate\020\005B\026\n\024org.libra." +
      "grpc.typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mempool_status_MempoolAddTransactionStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mempool_status_MempoolAddTransactionStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mempool_status_MempoolAddTransactionStatus_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
