// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validator_change.proto

package org.libra.grpc.types;

public final class ValidatorChange {
  private ValidatorChange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ValidatorChangeEventWithProofOrBuilder extends
      // @@protoc_insertion_point(interface_extends:types.ValidatorChangeEventWithProof)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    java.util.List<org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures> 
        getLedgerInfoWithSigsList();
    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures getLedgerInfoWithSigs(int index);
    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    int getLedgerInfoWithSigsCount();
    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    java.util.List<? extends org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder> 
        getLedgerInfoWithSigsOrBuilderList();
    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder getLedgerInfoWithSigsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * This is used to prove validator changes.  When a validator is changing, it
   * triggers an event on /validator_change_account/events/sent.  To tell the
   * client about validator changes, we query
   * /validator_change_account/events/sent to get all versions that contain
   * validator changes after the version that we are trying to update from. For
   * each of these versions, the old validator set would have signed the ledger
   * info at that version.  The client needs this as well as the event results +
   * proof.  The client can then verify that these events were under the current
   * tree and that the changes were signed by the old validators (and that the
   * events correctly show which validators are the new validators).
   * </pre>
   *
   * Protobuf type {@code types.ValidatorChangeEventWithProof}
   */
  public  static final class ValidatorChangeEventWithProof extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:types.ValidatorChangeEventWithProof)
      ValidatorChangeEventWithProofOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValidatorChangeEventWithProof.newBuilder() to construct.
    private ValidatorChangeEventWithProof(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidatorChangeEventWithProof() {
      ledgerInfoWithSigs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValidatorChangeEventWithProof(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                ledgerInfoWithSigs_ = new java.util.ArrayList<org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures>();
                mutable_bitField0_ |= 0x00000001;
              }
              ledgerInfoWithSigs_.add(
                  input.readMessage(org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          ledgerInfoWithSigs_ = java.util.Collections.unmodifiableList(ledgerInfoWithSigs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.libra.grpc.types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.libra.grpc.types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof.class, org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof.Builder.class);
    }

    public static final int LEDGER_INFO_WITH_SIGS_FIELD_NUMBER = 1;
    private java.util.List<org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures> ledgerInfoWithSigs_;
    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    public java.util.List<org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures> getLedgerInfoWithSigsList() {
      return ledgerInfoWithSigs_;
    }
    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    public java.util.List<? extends org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder> 
        getLedgerInfoWithSigsOrBuilderList() {
      return ledgerInfoWithSigs_;
    }
    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    public int getLedgerInfoWithSigsCount() {
      return ledgerInfoWithSigs_.size();
    }
    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    public org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures getLedgerInfoWithSigs(int index) {
      return ledgerInfoWithSigs_.get(index);
    }
    /**
     * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    public org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder getLedgerInfoWithSigsOrBuilder(
        int index) {
      return ledgerInfoWithSigs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < ledgerInfoWithSigs_.size(); i++) {
        output.writeMessage(1, ledgerInfoWithSigs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < ledgerInfoWithSigs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ledgerInfoWithSigs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof)) {
        return super.equals(obj);
      }
      org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof other = (org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof) obj;

      if (!getLedgerInfoWithSigsList()
          .equals(other.getLedgerInfoWithSigsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLedgerInfoWithSigsCount() > 0) {
        hash = (37 * hash) + LEDGER_INFO_WITH_SIGS_FIELD_NUMBER;
        hash = (53 * hash) + getLedgerInfoWithSigsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This is used to prove validator changes.  When a validator is changing, it
     * triggers an event on /validator_change_account/events/sent.  To tell the
     * client about validator changes, we query
     * /validator_change_account/events/sent to get all versions that contain
     * validator changes after the version that we are trying to update from. For
     * each of these versions, the old validator set would have signed the ledger
     * info at that version.  The client needs this as well as the event results +
     * proof.  The client can then verify that these events were under the current
     * tree and that the changes were signed by the old validators (and that the
     * events correctly show which validators are the new validators).
     * </pre>
     *
     * Protobuf type {@code types.ValidatorChangeEventWithProof}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:types.ValidatorChangeEventWithProof)
        org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProofOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.libra.grpc.types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.libra.grpc.types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof.class, org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof.Builder.class);
      }

      // Construct using org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLedgerInfoWithSigsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (ledgerInfoWithSigsBuilder_ == null) {
          ledgerInfoWithSigs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ledgerInfoWithSigsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.libra.grpc.types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_descriptor;
      }

      @java.lang.Override
      public org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof getDefaultInstanceForType() {
        return org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof.getDefaultInstance();
      }

      @java.lang.Override
      public org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof build() {
        org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof buildPartial() {
        org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof result = new org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof(this);
        int from_bitField0_ = bitField0_;
        if (ledgerInfoWithSigsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            ledgerInfoWithSigs_ = java.util.Collections.unmodifiableList(ledgerInfoWithSigs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.ledgerInfoWithSigs_ = ledgerInfoWithSigs_;
        } else {
          result.ledgerInfoWithSigs_ = ledgerInfoWithSigsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof) {
          return mergeFrom((org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof other) {
        if (other == org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof.getDefaultInstance()) return this;
        if (ledgerInfoWithSigsBuilder_ == null) {
          if (!other.ledgerInfoWithSigs_.isEmpty()) {
            if (ledgerInfoWithSigs_.isEmpty()) {
              ledgerInfoWithSigs_ = other.ledgerInfoWithSigs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLedgerInfoWithSigsIsMutable();
              ledgerInfoWithSigs_.addAll(other.ledgerInfoWithSigs_);
            }
            onChanged();
          }
        } else {
          if (!other.ledgerInfoWithSigs_.isEmpty()) {
            if (ledgerInfoWithSigsBuilder_.isEmpty()) {
              ledgerInfoWithSigsBuilder_.dispose();
              ledgerInfoWithSigsBuilder_ = null;
              ledgerInfoWithSigs_ = other.ledgerInfoWithSigs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ledgerInfoWithSigsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLedgerInfoWithSigsFieldBuilder() : null;
            } else {
              ledgerInfoWithSigsBuilder_.addAllMessages(other.ledgerInfoWithSigs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures> ledgerInfoWithSigs_ =
        java.util.Collections.emptyList();
      private void ensureLedgerInfoWithSigsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          ledgerInfoWithSigs_ = new java.util.ArrayList<org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures>(ledgerInfoWithSigs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder> ledgerInfoWithSigsBuilder_;

      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public java.util.List<org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures> getLedgerInfoWithSigsList() {
        if (ledgerInfoWithSigsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ledgerInfoWithSigs_);
        } else {
          return ledgerInfoWithSigsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public int getLedgerInfoWithSigsCount() {
        if (ledgerInfoWithSigsBuilder_ == null) {
          return ledgerInfoWithSigs_.size();
        } else {
          return ledgerInfoWithSigsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures getLedgerInfoWithSigs(int index) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          return ledgerInfoWithSigs_.get(index);
        } else {
          return ledgerInfoWithSigsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder setLedgerInfoWithSigs(
          int index, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures value) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLedgerInfoWithSigsIsMutable();
          ledgerInfoWithSigs_.set(index, value);
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder setLedgerInfoWithSigs(
          int index, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder builderForValue) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ensureLedgerInfoWithSigsIsMutable();
          ledgerInfoWithSigs_.set(index, builderForValue.build());
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder addLedgerInfoWithSigs(org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures value) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLedgerInfoWithSigsIsMutable();
          ledgerInfoWithSigs_.add(value);
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder addLedgerInfoWithSigs(
          int index, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures value) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLedgerInfoWithSigsIsMutable();
          ledgerInfoWithSigs_.add(index, value);
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder addLedgerInfoWithSigs(
          org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder builderForValue) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ensureLedgerInfoWithSigsIsMutable();
          ledgerInfoWithSigs_.add(builderForValue.build());
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder addLedgerInfoWithSigs(
          int index, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder builderForValue) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ensureLedgerInfoWithSigsIsMutable();
          ledgerInfoWithSigs_.add(index, builderForValue.build());
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder addAllLedgerInfoWithSigs(
          java.lang.Iterable<? extends org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures> values) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ensureLedgerInfoWithSigsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ledgerInfoWithSigs_);
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder clearLedgerInfoWithSigs() {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ledgerInfoWithSigs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder removeLedgerInfoWithSigs(int index) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ensureLedgerInfoWithSigsIsMutable();
          ledgerInfoWithSigs_.remove(index);
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder getLedgerInfoWithSigsBuilder(
          int index) {
        return getLedgerInfoWithSigsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder getLedgerInfoWithSigsOrBuilder(
          int index) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          return ledgerInfoWithSigs_.get(index);  } else {
          return ledgerInfoWithSigsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public java.util.List<? extends org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder> 
           getLedgerInfoWithSigsOrBuilderList() {
        if (ledgerInfoWithSigsBuilder_ != null) {
          return ledgerInfoWithSigsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ledgerInfoWithSigs_);
        }
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder addLedgerInfoWithSigsBuilder() {
        return getLedgerInfoWithSigsFieldBuilder().addBuilder(
            org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.getDefaultInstance());
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder addLedgerInfoWithSigsBuilder(
          int index) {
        return getLedgerInfoWithSigsFieldBuilder().addBuilder(
            index, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.getDefaultInstance());
      }
      /**
       * <code>repeated .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public java.util.List<org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder> 
           getLedgerInfoWithSigsBuilderList() {
        return getLedgerInfoWithSigsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder> 
          getLedgerInfoWithSigsFieldBuilder() {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ledgerInfoWithSigsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder, org.libra.grpc.types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder>(
                  ledgerInfoWithSigs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          ledgerInfoWithSigs_ = null;
        }
        return ledgerInfoWithSigsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:types.ValidatorChangeEventWithProof)
    }

    // @@protoc_insertion_point(class_scope:types.ValidatorChangeEventWithProof)
    private static final org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof();
    }

    public static org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidatorChangeEventWithProof>
        PARSER = new com.google.protobuf.AbstractParser<ValidatorChangeEventWithProof>() {
      @java.lang.Override
      public ValidatorChangeEventWithProof parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValidatorChangeEventWithProof(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidatorChangeEventWithProof> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidatorChangeEventWithProof> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.libra.grpc.types.ValidatorChange.ValidatorChangeEventWithProof getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ValidatorChangeEventWithProof_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ValidatorChangeEventWithProof_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026validator_change.proto\022\005types\032\021ledger_" +
      "info.proto\"_\n\035ValidatorChangeEventWithPr" +
      "oof\022>\n\025ledger_info_with_sigs\030\001 \003(\0132\037.typ" +
      "es.LedgerInfoWithSignaturesB\026\n\024org.libra" +
      ".grpc.typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.libra.grpc.types.LedgerInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_types_ValidatorChangeEventWithProof_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_types_ValidatorChangeEventWithProof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ValidatorChangeEventWithProof_descriptor,
        new java.lang.String[] { "LedgerInfoWithSigs", });
    org.libra.grpc.types.LedgerInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
