// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admission_control.proto

package org.libra.grpc.admission_control;

public final class AdmissionControlOuterClass {
  private AdmissionControlOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Additional statuses that are possible from admission control in addition
   * to VM statuses.
   * </pre>
   *
   * Protobuf enum {@code admission_control.AdmissionControlStatus}
   */
  public enum AdmissionControlStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Accepted = 0;</code>
     */
    Accepted(0),
    /**
     * <code>Blacklisted = 1;</code>
     */
    Blacklisted(1),
    /**
     * <code>Rejected = 2;</code>
     */
    Rejected(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Accepted = 0;</code>
     */
    public static final int Accepted_VALUE = 0;
    /**
     * <code>Blacklisted = 1;</code>
     */
    public static final int Blacklisted_VALUE = 1;
    /**
     * <code>Rejected = 2;</code>
     */
    public static final int Rejected_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AdmissionControlStatus valueOf(int value) {
      return forNumber(value);
    }

    public static AdmissionControlStatus forNumber(int value) {
      switch (value) {
        case 0: return Accepted;
        case 1: return Blacklisted;
        case 2: return Rejected;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AdmissionControlStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AdmissionControlStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AdmissionControlStatus>() {
            public AdmissionControlStatus findValueByNumber(int number) {
              return AdmissionControlStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.libra.grpc.admission_control.AdmissionControlOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final AdmissionControlStatus[] VALUES = values();

    public static AdmissionControlStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AdmissionControlStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:admission_control.AdmissionControlStatus)
  }

  public interface SubmitTransactionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:admission_control.SubmitTransactionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Transaction signed by wallet.
     * </pre>
     *
     * <code>.types.SignedTransaction signed_txn = 1;</code>
     */
    boolean hasSignedTxn();
    /**
     * <pre>
     * Transaction signed by wallet.
     * </pre>
     *
     * <code>.types.SignedTransaction signed_txn = 1;</code>
     */
    org.libra.grpc.types.Transaction.SignedTransaction getSignedTxn();
    /**
     * <pre>
     * Transaction signed by wallet.
     * </pre>
     *
     * <code>.types.SignedTransaction signed_txn = 1;</code>
     */
    org.libra.grpc.types.Transaction.SignedTransactionOrBuilder getSignedTxnOrBuilder();
  }
  /**
   * <pre>
   * -----------------------------------------------------------------------------
   * ---------------- Submit transaction
   * -----------------------------------------------------------------------------
   * The request for transaction submission.
   * </pre>
   *
   * Protobuf type {@code admission_control.SubmitTransactionRequest}
   */
  public  static final class SubmitTransactionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:admission_control.SubmitTransactionRequest)
      SubmitTransactionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubmitTransactionRequest.newBuilder() to construct.
    private SubmitTransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubmitTransactionRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubmitTransactionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.libra.grpc.types.Transaction.SignedTransaction.Builder subBuilder = null;
              if (signedTxn_ != null) {
                subBuilder = signedTxn_.toBuilder();
              }
              signedTxn_ = input.readMessage(org.libra.grpc.types.Transaction.SignedTransaction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(signedTxn_);
                signedTxn_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest.class, org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest.Builder.class);
    }

    public static final int SIGNED_TXN_FIELD_NUMBER = 1;
    private org.libra.grpc.types.Transaction.SignedTransaction signedTxn_;
    /**
     * <pre>
     * Transaction signed by wallet.
     * </pre>
     *
     * <code>.types.SignedTransaction signed_txn = 1;</code>
     */
    public boolean hasSignedTxn() {
      return signedTxn_ != null;
    }
    /**
     * <pre>
     * Transaction signed by wallet.
     * </pre>
     *
     * <code>.types.SignedTransaction signed_txn = 1;</code>
     */
    public org.libra.grpc.types.Transaction.SignedTransaction getSignedTxn() {
      return signedTxn_ == null ? org.libra.grpc.types.Transaction.SignedTransaction.getDefaultInstance() : signedTxn_;
    }
    /**
     * <pre>
     * Transaction signed by wallet.
     * </pre>
     *
     * <code>.types.SignedTransaction signed_txn = 1;</code>
     */
    public org.libra.grpc.types.Transaction.SignedTransactionOrBuilder getSignedTxnOrBuilder() {
      return getSignedTxn();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (signedTxn_ != null) {
        output.writeMessage(1, getSignedTxn());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (signedTxn_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSignedTxn());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest)) {
        return super.equals(obj);
      }
      org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest other = (org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest) obj;

      if (hasSignedTxn() != other.hasSignedTxn()) return false;
      if (hasSignedTxn()) {
        if (!getSignedTxn()
            .equals(other.getSignedTxn())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSignedTxn()) {
        hash = (37 * hash) + SIGNED_TXN_FIELD_NUMBER;
        hash = (53 * hash) + getSignedTxn().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * -----------------------------------------------------------------------------
     * ---------------- Submit transaction
     * -----------------------------------------------------------------------------
     * The request for transaction submission.
     * </pre>
     *
     * Protobuf type {@code admission_control.SubmitTransactionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:admission_control.SubmitTransactionRequest)
        org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest.class, org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest.Builder.class);
      }

      // Construct using org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (signedTxnBuilder_ == null) {
          signedTxn_ = null;
        } else {
          signedTxn_ = null;
          signedTxnBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionRequest_descriptor;
      }

      @java.lang.Override
      public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest getDefaultInstanceForType() {
        return org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest build() {
        org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest buildPartial() {
        org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest result = new org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest(this);
        if (signedTxnBuilder_ == null) {
          result.signedTxn_ = signedTxn_;
        } else {
          result.signedTxn_ = signedTxnBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest) {
          return mergeFrom((org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest other) {
        if (other == org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest.getDefaultInstance()) return this;
        if (other.hasSignedTxn()) {
          mergeSignedTxn(other.getSignedTxn());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.libra.grpc.types.Transaction.SignedTransaction signedTxn_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.libra.grpc.types.Transaction.SignedTransaction, org.libra.grpc.types.Transaction.SignedTransaction.Builder, org.libra.grpc.types.Transaction.SignedTransactionOrBuilder> signedTxnBuilder_;
      /**
       * <pre>
       * Transaction signed by wallet.
       * </pre>
       *
       * <code>.types.SignedTransaction signed_txn = 1;</code>
       */
      public boolean hasSignedTxn() {
        return signedTxnBuilder_ != null || signedTxn_ != null;
      }
      /**
       * <pre>
       * Transaction signed by wallet.
       * </pre>
       *
       * <code>.types.SignedTransaction signed_txn = 1;</code>
       */
      public org.libra.grpc.types.Transaction.SignedTransaction getSignedTxn() {
        if (signedTxnBuilder_ == null) {
          return signedTxn_ == null ? org.libra.grpc.types.Transaction.SignedTransaction.getDefaultInstance() : signedTxn_;
        } else {
          return signedTxnBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Transaction signed by wallet.
       * </pre>
       *
       * <code>.types.SignedTransaction signed_txn = 1;</code>
       */
      public Builder setSignedTxn(org.libra.grpc.types.Transaction.SignedTransaction value) {
        if (signedTxnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          signedTxn_ = value;
          onChanged();
        } else {
          signedTxnBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Transaction signed by wallet.
       * </pre>
       *
       * <code>.types.SignedTransaction signed_txn = 1;</code>
       */
      public Builder setSignedTxn(
          org.libra.grpc.types.Transaction.SignedTransaction.Builder builderForValue) {
        if (signedTxnBuilder_ == null) {
          signedTxn_ = builderForValue.build();
          onChanged();
        } else {
          signedTxnBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Transaction signed by wallet.
       * </pre>
       *
       * <code>.types.SignedTransaction signed_txn = 1;</code>
       */
      public Builder mergeSignedTxn(org.libra.grpc.types.Transaction.SignedTransaction value) {
        if (signedTxnBuilder_ == null) {
          if (signedTxn_ != null) {
            signedTxn_ =
              org.libra.grpc.types.Transaction.SignedTransaction.newBuilder(signedTxn_).mergeFrom(value).buildPartial();
          } else {
            signedTxn_ = value;
          }
          onChanged();
        } else {
          signedTxnBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Transaction signed by wallet.
       * </pre>
       *
       * <code>.types.SignedTransaction signed_txn = 1;</code>
       */
      public Builder clearSignedTxn() {
        if (signedTxnBuilder_ == null) {
          signedTxn_ = null;
          onChanged();
        } else {
          signedTxn_ = null;
          signedTxnBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Transaction signed by wallet.
       * </pre>
       *
       * <code>.types.SignedTransaction signed_txn = 1;</code>
       */
      public org.libra.grpc.types.Transaction.SignedTransaction.Builder getSignedTxnBuilder() {
        
        onChanged();
        return getSignedTxnFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Transaction signed by wallet.
       * </pre>
       *
       * <code>.types.SignedTransaction signed_txn = 1;</code>
       */
      public org.libra.grpc.types.Transaction.SignedTransactionOrBuilder getSignedTxnOrBuilder() {
        if (signedTxnBuilder_ != null) {
          return signedTxnBuilder_.getMessageOrBuilder();
        } else {
          return signedTxn_ == null ?
              org.libra.grpc.types.Transaction.SignedTransaction.getDefaultInstance() : signedTxn_;
        }
      }
      /**
       * <pre>
       * Transaction signed by wallet.
       * </pre>
       *
       * <code>.types.SignedTransaction signed_txn = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.libra.grpc.types.Transaction.SignedTransaction, org.libra.grpc.types.Transaction.SignedTransaction.Builder, org.libra.grpc.types.Transaction.SignedTransactionOrBuilder> 
          getSignedTxnFieldBuilder() {
        if (signedTxnBuilder_ == null) {
          signedTxnBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.libra.grpc.types.Transaction.SignedTransaction, org.libra.grpc.types.Transaction.SignedTransaction.Builder, org.libra.grpc.types.Transaction.SignedTransactionOrBuilder>(
                  getSignedTxn(),
                  getParentForChildren(),
                  isClean());
          signedTxn_ = null;
        }
        return signedTxnBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:admission_control.SubmitTransactionRequest)
    }

    // @@protoc_insertion_point(class_scope:admission_control.SubmitTransactionRequest)
    private static final org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest();
    }

    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubmitTransactionRequest>
        PARSER = new com.google.protobuf.AbstractParser<SubmitTransactionRequest>() {
      @java.lang.Override
      public SubmitTransactionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubmitTransactionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubmitTransactionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubmitTransactionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubmitTransactionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:admission_control.SubmitTransactionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.types.VMStatus vm_status = 1;</code>
     */
    boolean hasVmStatus();
    /**
     * <code>.types.VMStatus vm_status = 1;</code>
     */
    org.libra.grpc.types.VmErrors.VMStatus getVmStatus();
    /**
     * <code>.types.VMStatus vm_status = 1;</code>
     */
    org.libra.grpc.types.VmErrors.VMStatusOrBuilder getVmStatusOrBuilder();

    /**
     * <code>.admission_control.AdmissionControlStatus ac_status = 2;</code>
     */
    int getAcStatusValue();
    /**
     * <code>.admission_control.AdmissionControlStatus ac_status = 2;</code>
     */
    org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus getAcStatus();

    /**
     * <code>.mempool.MempoolAddTransactionStatus mempool_status = 3;</code>
     */
    int getMempoolStatusValue();
    /**
     * <code>.mempool.MempoolAddTransactionStatus mempool_status = 3;</code>
     */
    org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus getMempoolStatus();

    /**
     * <pre>
     * Public key(id) of the validator that processed this transaction
     * </pre>
     *
     * <code>bytes validator_id = 4;</code>
     */
    com.google.protobuf.ByteString getValidatorId();

    public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.StatusCase getStatusCase();
  }
  /**
   * <pre>
   * The response for transaction submission.
   * How does a client know if their transaction was included?
   * A response from the transaction submission only means that the transaction
   * was successfully added to mempool, but not that it is guaranteed to be
   * included in the chain.  Each transaction should include an expiration time in
   * the signed transaction.  Let's call this T0.  As a client, I submit my
   * transaction to a validator. I now need to poll for the transaction I
   * submitted.  I can use the query that takes my account and sequence number. If
   * I receive back that the transaction is completed, I will verify the proofs to
   * ensure that this is the transaction I expected.  If I receive a response that
   * my transaction is not yet completed, I must check the latest timestamp in the
   * ledgerInfo that I receive back from the query.  If this time is greater than
   * T0, I can be certain that my transaction will never be included.  If this
   * time is less than T0, I need to continue polling.
   * </pre>
   *
   * Protobuf type {@code admission_control.SubmitTransactionResponse}
   */
  public  static final class SubmitTransactionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:admission_control.SubmitTransactionResponse)
      SubmitTransactionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubmitTransactionResponse.newBuilder() to construct.
    private SubmitTransactionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubmitTransactionResponse() {
      validatorId_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubmitTransactionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.libra.grpc.types.VmErrors.VMStatus.Builder subBuilder = null;
              if (statusCase_ == 1) {
                subBuilder = ((org.libra.grpc.types.VmErrors.VMStatus) status_).toBuilder();
              }
              status_ =
                  input.readMessage(org.libra.grpc.types.VmErrors.VMStatus.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((org.libra.grpc.types.VmErrors.VMStatus) status_);
                status_ = subBuilder.buildPartial();
              }
              statusCase_ = 1;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              statusCase_ = 2;
              status_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              statusCase_ = 3;
              status_ = rawValue;
              break;
            }
            case 34: {

              validatorId_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.class, org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.Builder.class);
    }

    private int statusCase_ = 0;
    private java.lang.Object status_;
    public enum StatusCase
        implements com.google.protobuf.Internal.EnumLite {
      VM_STATUS(1),
      AC_STATUS(2),
      MEMPOOL_STATUS(3),
      STATUS_NOT_SET(0);
      private final int value;
      private StatusCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static StatusCase valueOf(int value) {
        return forNumber(value);
      }

      public static StatusCase forNumber(int value) {
        switch (value) {
          case 1: return VM_STATUS;
          case 2: return AC_STATUS;
          case 3: return MEMPOOL_STATUS;
          case 0: return STATUS_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public StatusCase
    getStatusCase() {
      return StatusCase.forNumber(
          statusCase_);
    }

    public static final int VM_STATUS_FIELD_NUMBER = 1;
    /**
     * <code>.types.VMStatus vm_status = 1;</code>
     */
    public boolean hasVmStatus() {
      return statusCase_ == 1;
    }
    /**
     * <code>.types.VMStatus vm_status = 1;</code>
     */
    public org.libra.grpc.types.VmErrors.VMStatus getVmStatus() {
      if (statusCase_ == 1) {
         return (org.libra.grpc.types.VmErrors.VMStatus) status_;
      }
      return org.libra.grpc.types.VmErrors.VMStatus.getDefaultInstance();
    }
    /**
     * <code>.types.VMStatus vm_status = 1;</code>
     */
    public org.libra.grpc.types.VmErrors.VMStatusOrBuilder getVmStatusOrBuilder() {
      if (statusCase_ == 1) {
         return (org.libra.grpc.types.VmErrors.VMStatus) status_;
      }
      return org.libra.grpc.types.VmErrors.VMStatus.getDefaultInstance();
    }

    public static final int AC_STATUS_FIELD_NUMBER = 2;
    /**
     * <code>.admission_control.AdmissionControlStatus ac_status = 2;</code>
     */
    public int getAcStatusValue() {
      if (statusCase_ == 2) {
        return (java.lang.Integer) status_;
      }
      return 0;
    }
    /**
     * <code>.admission_control.AdmissionControlStatus ac_status = 2;</code>
     */
    public org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus getAcStatus() {
      if (statusCase_ == 2) {
        @SuppressWarnings("deprecation")
        org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus result = org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus.valueOf(
            (java.lang.Integer) status_);
        return result == null ? org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus.UNRECOGNIZED : result;
      }
      return org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus.Accepted;
    }

    public static final int MEMPOOL_STATUS_FIELD_NUMBER = 3;
    /**
     * <code>.mempool.MempoolAddTransactionStatus mempool_status = 3;</code>
     */
    public int getMempoolStatusValue() {
      if (statusCase_ == 3) {
        return (java.lang.Integer) status_;
      }
      return 0;
    }
    /**
     * <code>.mempool.MempoolAddTransactionStatus mempool_status = 3;</code>
     */
    public org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus getMempoolStatus() {
      if (statusCase_ == 3) {
        @SuppressWarnings("deprecation")
        org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus result = org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus.valueOf(
            (java.lang.Integer) status_);
        return result == null ? org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus.UNRECOGNIZED : result;
      }
      return org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus.Valid;
    }

    public static final int VALIDATOR_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString validatorId_;
    /**
     * <pre>
     * Public key(id) of the validator that processed this transaction
     * </pre>
     *
     * <code>bytes validator_id = 4;</code>
     */
    public com.google.protobuf.ByteString getValidatorId() {
      return validatorId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (statusCase_ == 1) {
        output.writeMessage(1, (org.libra.grpc.types.VmErrors.VMStatus) status_);
      }
      if (statusCase_ == 2) {
        output.writeEnum(2, ((java.lang.Integer) status_));
      }
      if (statusCase_ == 3) {
        output.writeEnum(3, ((java.lang.Integer) status_));
      }
      if (!validatorId_.isEmpty()) {
        output.writeBytes(4, validatorId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (statusCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (org.libra.grpc.types.VmErrors.VMStatus) status_);
      }
      if (statusCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, ((java.lang.Integer) status_));
      }
      if (statusCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, ((java.lang.Integer) status_));
      }
      if (!validatorId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, validatorId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse)) {
        return super.equals(obj);
      }
      org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse other = (org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse) obj;

      if (!getValidatorId()
          .equals(other.getValidatorId())) return false;
      if (!getStatusCase().equals(other.getStatusCase())) return false;
      switch (statusCase_) {
        case 1:
          if (!getVmStatus()
              .equals(other.getVmStatus())) return false;
          break;
        case 2:
          if (getAcStatusValue()
              != other.getAcStatusValue()) return false;
          break;
        case 3:
          if (getMempoolStatusValue()
              != other.getMempoolStatusValue()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALIDATOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getValidatorId().hashCode();
      switch (statusCase_) {
        case 1:
          hash = (37 * hash) + VM_STATUS_FIELD_NUMBER;
          hash = (53 * hash) + getVmStatus().hashCode();
          break;
        case 2:
          hash = (37 * hash) + AC_STATUS_FIELD_NUMBER;
          hash = (53 * hash) + getAcStatusValue();
          break;
        case 3:
          hash = (37 * hash) + MEMPOOL_STATUS_FIELD_NUMBER;
          hash = (53 * hash) + getMempoolStatusValue();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response for transaction submission.
     * How does a client know if their transaction was included?
     * A response from the transaction submission only means that the transaction
     * was successfully added to mempool, but not that it is guaranteed to be
     * included in the chain.  Each transaction should include an expiration time in
     * the signed transaction.  Let's call this T0.  As a client, I submit my
     * transaction to a validator. I now need to poll for the transaction I
     * submitted.  I can use the query that takes my account and sequence number. If
     * I receive back that the transaction is completed, I will verify the proofs to
     * ensure that this is the transaction I expected.  If I receive a response that
     * my transaction is not yet completed, I must check the latest timestamp in the
     * ledgerInfo that I receive back from the query.  If this time is greater than
     * T0, I can be certain that my transaction will never be included.  If this
     * time is less than T0, I need to continue polling.
     * </pre>
     *
     * Protobuf type {@code admission_control.SubmitTransactionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:admission_control.SubmitTransactionResponse)
        org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.class, org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.Builder.class);
      }

      // Construct using org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        validatorId_ = com.google.protobuf.ByteString.EMPTY;

        statusCase_ = 0;
        status_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.libra.grpc.admission_control.AdmissionControlOuterClass.internal_static_admission_control_SubmitTransactionResponse_descriptor;
      }

      @java.lang.Override
      public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse getDefaultInstanceForType() {
        return org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse build() {
        org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse buildPartial() {
        org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse result = new org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse(this);
        if (statusCase_ == 1) {
          if (vmStatusBuilder_ == null) {
            result.status_ = status_;
          } else {
            result.status_ = vmStatusBuilder_.build();
          }
        }
        if (statusCase_ == 2) {
          result.status_ = status_;
        }
        if (statusCase_ == 3) {
          result.status_ = status_;
        }
        result.validatorId_ = validatorId_;
        result.statusCase_ = statusCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse) {
          return mergeFrom((org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse other) {
        if (other == org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.getDefaultInstance()) return this;
        if (other.getValidatorId() != com.google.protobuf.ByteString.EMPTY) {
          setValidatorId(other.getValidatorId());
        }
        switch (other.getStatusCase()) {
          case VM_STATUS: {
            mergeVmStatus(other.getVmStatus());
            break;
          }
          case AC_STATUS: {
            setAcStatusValue(other.getAcStatusValue());
            break;
          }
          case MEMPOOL_STATUS: {
            setMempoolStatusValue(other.getMempoolStatusValue());
            break;
          }
          case STATUS_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int statusCase_ = 0;
      private java.lang.Object status_;
      public StatusCase
          getStatusCase() {
        return StatusCase.forNumber(
            statusCase_);
      }

      public Builder clearStatus() {
        statusCase_ = 0;
        status_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          org.libra.grpc.types.VmErrors.VMStatus, org.libra.grpc.types.VmErrors.VMStatus.Builder, org.libra.grpc.types.VmErrors.VMStatusOrBuilder> vmStatusBuilder_;
      /**
       * <code>.types.VMStatus vm_status = 1;</code>
       */
      public boolean hasVmStatus() {
        return statusCase_ == 1;
      }
      /**
       * <code>.types.VMStatus vm_status = 1;</code>
       */
      public org.libra.grpc.types.VmErrors.VMStatus getVmStatus() {
        if (vmStatusBuilder_ == null) {
          if (statusCase_ == 1) {
            return (org.libra.grpc.types.VmErrors.VMStatus) status_;
          }
          return org.libra.grpc.types.VmErrors.VMStatus.getDefaultInstance();
        } else {
          if (statusCase_ == 1) {
            return vmStatusBuilder_.getMessage();
          }
          return org.libra.grpc.types.VmErrors.VMStatus.getDefaultInstance();
        }
      }
      /**
       * <code>.types.VMStatus vm_status = 1;</code>
       */
      public Builder setVmStatus(org.libra.grpc.types.VmErrors.VMStatus value) {
        if (vmStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          vmStatusBuilder_.setMessage(value);
        }
        statusCase_ = 1;
        return this;
      }
      /**
       * <code>.types.VMStatus vm_status = 1;</code>
       */
      public Builder setVmStatus(
          org.libra.grpc.types.VmErrors.VMStatus.Builder builderForValue) {
        if (vmStatusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          vmStatusBuilder_.setMessage(builderForValue.build());
        }
        statusCase_ = 1;
        return this;
      }
      /**
       * <code>.types.VMStatus vm_status = 1;</code>
       */
      public Builder mergeVmStatus(org.libra.grpc.types.VmErrors.VMStatus value) {
        if (vmStatusBuilder_ == null) {
          if (statusCase_ == 1 &&
              status_ != org.libra.grpc.types.VmErrors.VMStatus.getDefaultInstance()) {
            status_ = org.libra.grpc.types.VmErrors.VMStatus.newBuilder((org.libra.grpc.types.VmErrors.VMStatus) status_)
                .mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          if (statusCase_ == 1) {
            vmStatusBuilder_.mergeFrom(value);
          }
          vmStatusBuilder_.setMessage(value);
        }
        statusCase_ = 1;
        return this;
      }
      /**
       * <code>.types.VMStatus vm_status = 1;</code>
       */
      public Builder clearVmStatus() {
        if (vmStatusBuilder_ == null) {
          if (statusCase_ == 1) {
            statusCase_ = 0;
            status_ = null;
            onChanged();
          }
        } else {
          if (statusCase_ == 1) {
            statusCase_ = 0;
            status_ = null;
          }
          vmStatusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.types.VMStatus vm_status = 1;</code>
       */
      public org.libra.grpc.types.VmErrors.VMStatus.Builder getVmStatusBuilder() {
        return getVmStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>.types.VMStatus vm_status = 1;</code>
       */
      public org.libra.grpc.types.VmErrors.VMStatusOrBuilder getVmStatusOrBuilder() {
        if ((statusCase_ == 1) && (vmStatusBuilder_ != null)) {
          return vmStatusBuilder_.getMessageOrBuilder();
        } else {
          if (statusCase_ == 1) {
            return (org.libra.grpc.types.VmErrors.VMStatus) status_;
          }
          return org.libra.grpc.types.VmErrors.VMStatus.getDefaultInstance();
        }
      }
      /**
       * <code>.types.VMStatus vm_status = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.libra.grpc.types.VmErrors.VMStatus, org.libra.grpc.types.VmErrors.VMStatus.Builder, org.libra.grpc.types.VmErrors.VMStatusOrBuilder> 
          getVmStatusFieldBuilder() {
        if (vmStatusBuilder_ == null) {
          if (!(statusCase_ == 1)) {
            status_ = org.libra.grpc.types.VmErrors.VMStatus.getDefaultInstance();
          }
          vmStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.libra.grpc.types.VmErrors.VMStatus, org.libra.grpc.types.VmErrors.VMStatus.Builder, org.libra.grpc.types.VmErrors.VMStatusOrBuilder>(
                  (org.libra.grpc.types.VmErrors.VMStatus) status_,
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        statusCase_ = 1;
        onChanged();;
        return vmStatusBuilder_;
      }

      /**
       * <code>.admission_control.AdmissionControlStatus ac_status = 2;</code>
       */
      public int getAcStatusValue() {
        if (statusCase_ == 2) {
          return ((java.lang.Integer) status_).intValue();
        }
        return 0;
      }
      /**
       * <code>.admission_control.AdmissionControlStatus ac_status = 2;</code>
       */
      public Builder setAcStatusValue(int value) {
        statusCase_ = 2;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.admission_control.AdmissionControlStatus ac_status = 2;</code>
       */
      public org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus getAcStatus() {
        if (statusCase_ == 2) {
          @SuppressWarnings("deprecation")
          org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus result = org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus.valueOf(
              (java.lang.Integer) status_);
          return result == null ? org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus.UNRECOGNIZED : result;
        }
        return org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus.Accepted;
      }
      /**
       * <code>.admission_control.AdmissionControlStatus ac_status = 2;</code>
       */
      public Builder setAcStatus(org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControlStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        statusCase_ = 2;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.admission_control.AdmissionControlStatus ac_status = 2;</code>
       */
      public Builder clearAcStatus() {
        if (statusCase_ == 2) {
          statusCase_ = 0;
          status_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>.mempool.MempoolAddTransactionStatus mempool_status = 3;</code>
       */
      public int getMempoolStatusValue() {
        if (statusCase_ == 3) {
          return ((java.lang.Integer) status_).intValue();
        }
        return 0;
      }
      /**
       * <code>.mempool.MempoolAddTransactionStatus mempool_status = 3;</code>
       */
      public Builder setMempoolStatusValue(int value) {
        statusCase_ = 3;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.mempool.MempoolAddTransactionStatus mempool_status = 3;</code>
       */
      public org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus getMempoolStatus() {
        if (statusCase_ == 3) {
          @SuppressWarnings("deprecation")
          org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus result = org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus.valueOf(
              (java.lang.Integer) status_);
          return result == null ? org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus.UNRECOGNIZED : result;
        }
        return org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus.Valid;
      }
      /**
       * <code>.mempool.MempoolAddTransactionStatus mempool_status = 3;</code>
       */
      public Builder setMempoolStatus(org.libra.grpc.mempool.MempoolStatus.MempoolAddTransactionStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        statusCase_ = 3;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.mempool.MempoolAddTransactionStatus mempool_status = 3;</code>
       */
      public Builder clearMempoolStatus() {
        if (statusCase_ == 3) {
          statusCase_ = 0;
          status_ = null;
          onChanged();
        }
        return this;
      }

      private com.google.protobuf.ByteString validatorId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Public key(id) of the validator that processed this transaction
       * </pre>
       *
       * <code>bytes validator_id = 4;</code>
       */
      public com.google.protobuf.ByteString getValidatorId() {
        return validatorId_;
      }
      /**
       * <pre>
       * Public key(id) of the validator that processed this transaction
       * </pre>
       *
       * <code>bytes validator_id = 4;</code>
       */
      public Builder setValidatorId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        validatorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Public key(id) of the validator that processed this transaction
       * </pre>
       *
       * <code>bytes validator_id = 4;</code>
       */
      public Builder clearValidatorId() {
        
        validatorId_ = getDefaultInstance().getValidatorId();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:admission_control.SubmitTransactionResponse)
    }

    // @@protoc_insertion_point(class_scope:admission_control.SubmitTransactionResponse)
    private static final org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse();
    }

    public static org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubmitTransactionResponse>
        PARSER = new com.google.protobuf.AbstractParser<SubmitTransactionResponse>() {
      @java.lang.Override
      public SubmitTransactionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubmitTransactionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubmitTransactionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubmitTransactionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * <pre>
   * -----------------------------------------------------------------------------
   * ---------------- Service definition
   * -----------------------------------------------------------------------------
   * </pre>
   *
   * Protobuf service {@code admission_control.AdmissionControl}
   */
  public static abstract class AdmissionControl
      implements com.google.protobuf.Service {
    protected AdmissionControl() {}

    public interface Interface {
      /**
       * <pre>
       * Public API to submit transaction to a validator.
       * </pre>
       *
       * <code>rpc SubmitTransaction(.admission_control.SubmitTransactionRequest) returns (.admission_control.SubmitTransactionResponse);</code>
       */
      public abstract void submitTransaction(
          com.google.protobuf.RpcController controller,
          org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest request,
          com.google.protobuf.RpcCallback<org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse> done);

      /**
       * <pre>
       * This API is used to update the client to the latest ledger version and
       * optionally also request 1..n other pieces of data.  This allows for batch
       * queries.  All queries return proofs that a client should check to validate
       * the data. Note that if a client only wishes to update to the latest
       * LedgerInfo and receive the proof of this latest version, they can simply
       * omit the requested_items (or pass an empty list)
       * </pre>
       *
       * <code>rpc UpdateToLatestLedger(.types.UpdateToLatestLedgerRequest) returns (.types.UpdateToLatestLedgerResponse);</code>
       */
      public abstract void updateToLatestLedger(
          com.google.protobuf.RpcController controller,
          org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest request,
          com.google.protobuf.RpcCallback<org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new AdmissionControl() {
        @java.lang.Override
        public  void submitTransaction(
            com.google.protobuf.RpcController controller,
            org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest request,
            com.google.protobuf.RpcCallback<org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse> done) {
          impl.submitTransaction(controller, request, done);
        }

        @java.lang.Override
        public  void updateToLatestLedger(
            com.google.protobuf.RpcController controller,
            org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest request,
            com.google.protobuf.RpcCallback<org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse> done) {
          impl.updateToLatestLedger(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.submitTransaction(controller, (org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest)request);
            case 1:
              return impl.updateToLatestLedger(controller, (org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest.getDefaultInstance();
            case 1:
              return org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.getDefaultInstance();
            case 1:
              return org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <pre>
     * Public API to submit transaction to a validator.
     * </pre>
     *
     * <code>rpc SubmitTransaction(.admission_control.SubmitTransactionRequest) returns (.admission_control.SubmitTransactionResponse);</code>
     */
    public abstract void submitTransaction(
        com.google.protobuf.RpcController controller,
        org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest request,
        com.google.protobuf.RpcCallback<org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse> done);

    /**
     * <pre>
     * This API is used to update the client to the latest ledger version and
     * optionally also request 1..n other pieces of data.  This allows for batch
     * queries.  All queries return proofs that a client should check to validate
     * the data. Note that if a client only wishes to update to the latest
     * LedgerInfo and receive the proof of this latest version, they can simply
     * omit the requested_items (or pass an empty list)
     * </pre>
     *
     * <code>rpc UpdateToLatestLedger(.types.UpdateToLatestLedgerRequest) returns (.types.UpdateToLatestLedgerResponse);</code>
     */
    public abstract void updateToLatestLedger(
        com.google.protobuf.RpcController controller,
        org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest request,
        com.google.protobuf.RpcCallback<org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.libra.grpc.admission_control.AdmissionControlOuterClass.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.submitTransaction(controller, (org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest)request,
            com.google.protobuf.RpcUtil.<org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse>specializeCallback(
              done));
          return;
        case 1:
          this.updateToLatestLedger(controller, (org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest)request,
            com.google.protobuf.RpcUtil.<org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest.getDefaultInstance();
        case 1:
          return org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.getDefaultInstance();
        case 1:
          return org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.libra.grpc.admission_control.AdmissionControlOuterClass.AdmissionControl implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void submitTransaction(
          com.google.protobuf.RpcController controller,
          org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest request,
          com.google.protobuf.RpcCallback<org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.class,
            org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.getDefaultInstance()));
      }

      public  void updateToLatestLedger(
          com.google.protobuf.RpcController controller,
          org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest request,
          com.google.protobuf.RpcCallback<org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse.class,
            org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse submitTransaction(
          com.google.protobuf.RpcController controller,
          org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest request)
          throws com.google.protobuf.ServiceException;

      public org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse updateToLatestLedger(
          com.google.protobuf.RpcController controller,
          org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse submitTransaction(
          com.google.protobuf.RpcController controller,
          org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.libra.grpc.admission_control.AdmissionControlOuterClass.SubmitTransactionResponse.getDefaultInstance());
      }


      public org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse updateToLatestLedger(
          com.google.protobuf.RpcController controller,
          org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.libra.grpc.types.GetWithProof.UpdateToLatestLedgerResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:admission_control.AdmissionControl)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_admission_control_SubmitTransactionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_admission_control_SubmitTransactionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_admission_control_SubmitTransactionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_admission_control_SubmitTransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027admission_control.proto\022\021admission_con" +
      "trol\032\024get_with_proof.proto\032\021transaction." +
      "proto\032\013proof.proto\032\021ledger_info.proto\032\017v" +
      "m_errors.proto\032\024mempool_status.proto\"H\n\030" +
      "SubmitTransactionRequest\022,\n\nsigned_txn\030\001" +
      " \001(\0132\030.types.SignedTransaction\"\341\001\n\031Submi" +
      "tTransactionResponse\022$\n\tvm_status\030\001 \001(\0132" +
      "\017.types.VMStatusH\000\022>\n\tac_status\030\002 \001(\0162)." +
      "admission_control.AdmissionControlStatus" +
      "H\000\022>\n\016mempool_status\030\003 \001(\0162$.mempool.Mem" +
      "poolAddTransactionStatusH\000\022\024\n\014validator_" +
      "id\030\004 \001(\014B\010\n\006status*E\n\026AdmissionControlSt" +
      "atus\022\014\n\010Accepted\020\000\022\017\n\013Blacklisted\020\001\022\014\n\010R" +
      "ejected\020\0022\347\001\n\020AdmissionControl\022p\n\021Submit" +
      "Transaction\022+.admission_control.SubmitTr" +
      "ansactionRequest\032,.admission_control.Sub" +
      "mitTransactionResponse\"\000\022a\n\024UpdateToLate" +
      "stLedger\022\".types.UpdateToLatestLedgerReq" +
      "uest\032#.types.UpdateToLatestLedgerRespons" +
      "e\"\000B%\n org.libra.grpc.admission_control\210" +
      "\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.libra.grpc.types.GetWithProof.getDescriptor(),
          org.libra.grpc.types.Transaction.getDescriptor(),
          org.libra.grpc.types.Proof.getDescriptor(),
          org.libra.grpc.types.LedgerInfoOuterClass.getDescriptor(),
          org.libra.grpc.types.VmErrors.getDescriptor(),
          org.libra.grpc.mempool.MempoolStatus.getDescriptor(),
        }, assigner);
    internal_static_admission_control_SubmitTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_admission_control_SubmitTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_admission_control_SubmitTransactionRequest_descriptor,
        new java.lang.String[] { "SignedTxn", });
    internal_static_admission_control_SubmitTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_admission_control_SubmitTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_admission_control_SubmitTransactionResponse_descriptor,
        new java.lang.String[] { "VmStatus", "AcStatus", "MempoolStatus", "ValidatorId", "Status", });
    org.libra.grpc.types.GetWithProof.getDescriptor();
    org.libra.grpc.types.Transaction.getDescriptor();
    org.libra.grpc.types.Proof.getDescriptor();
    org.libra.grpc.types.LedgerInfoOuterClass.getDescriptor();
    org.libra.grpc.types.VmErrors.getDescriptor();
    org.libra.grpc.mempool.MempoolStatus.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
